### ISSUE TITLE
Switch foreman-operations-collection to testing with Alma

### ISSUE THREAD

**Issue by ehelms** [theforeman/foreman-operations-collection#167]

**Comment by ekohl** [comment]
The various molecule files refer to CentOS 8 Stream, like:
https://github.com/theforeman/foreman-operations-collection/blob/d3ee7fd15ad47f7a31602c09ca697f9a8390f7c5/roles/backup/molecule/redhat/molecule.yml#L6-L8

Since we're going to drop EL8 with Foreman 3.13 it may be sufficient to only test on CentOS 9 Stream. @evgeni will have an opinion on this.
